### ISSUE TITLE
Utdaterad dependency

### ISSUE THREAD

**Issue by Pro9** [Phelerox/file-hosting-site#1]
Någon dependency verkar använda sig av en utdaterad version av facelets, kan leda till problem.

Edit: Verkar vara tomahawk som ger dessa fel(kopierar in ett av flera, vet ej om det ställer till några problem):

Varning: JSF1029:  Application is versioned at 2.0 (either explicitly by the version of /WEB-INF/faces-config.xml or the lack of a /WEB-INF/faces-confg.xml), however class 'org.apache.myfaces.custom.aliasbean.AliasBeanTagHandler' depends on a legacy facelet class.  The facelet artifact represented by this class will not be registered.

**Comment by Phelerox** [comment]
Det här är fixat i senaste committen.
